import type { TravelDNAQuestion, TravelDNAArchetype, Destination } from "./types";

export const BRAND_COLORS = {
  teapDeep: "#0D7377",
  tealBright: "#14A3A8",
  tealLight: "#B2E4E6",
  peach: "#F4845F",
  peachLight: "#F7B89C",
  peachPale: "#FDE8DF",
  charcoal: "#2D3436",
  slate: "#636E72",
  silver: "#B2BEC3",
  cloud: "#F5F6FA",
  ocean: "#0A5C5E",
  coral: "#E17055",
  mint: "#55EFC4",
  sand: "#FFEAA7",
};

export const TRAVEL_DNA_QUESTIONS: TravelDNAQuestion[] = [
  {
    id: 1,
    axis: "social",
    question: "Your ideal evening?",
    optionA: {
      label: "Bustling night market",
      emoji: "🌃",
      gradientFrom: "from-teal-deep",
      gradientTo: "to-teal-bright",
      value: 1,
    },
    optionB: {
      label: "Quiet sunset dinner",
      emoji: "🌅",
      gradientFrom: "from-peach",
      gradientTo: "to-peach-light",
      value: -1,
    },
  },
  {
    id: 2,
    axis: "adventure",
    question: "How do you start your travel days?",
    optionA: {
      label: "Wake up early for a hike",
      emoji: "🏔️",
      gradientFrom: "from-teal-bright",
      gradientTo: "to-mint",
      value: 1,
    },
    optionB: {
      label: "Sleep in, brunch at noon",
      emoji: "🥐",
      gradientFrom: "from-peach-light",
      gradientTo: "to-peach-pale",
      value: -1,
    },
  },
  {
    id: 3,
    axis: "structure",
    question: "When exploring a new place?",
    optionA: {
      label: "Guided tour with a local",
      emoji: "👨-🏫",
      gradientFrom: "from-teal-deep",
      gradientTo: "to-ocean",
      value: 1,
    },
    optionB: {
      label: "Wander and get lost",
      emoji: "🗺️",
      gradientFrom: "from-coral",
      gradientTo: "to-peach",
      value: -1,
    },
  },
  {
    id: 4,
    axis: "cultural",
    question: "Where do you feel at home?",
    optionA: {
      label: "Mountain cabin",
      emoji: "🏔️",
      gradientFrom: "from-teal-bright",
      gradientTo: "to-teal-light",
      value: -1,
    },
    optionB: {
      label: "Beachfront villa",
      emoji: "🏝️",
      gradientFrom: "from-peach",
      gradientTo: "to-sand",
      value: 1,
    },
  },
  {
    id: 5,
    axis: "budget",
    question: "How do you eat while traveling?",
    optionA: {
      label: "Street food crawl",
      emoji: "🌮",
      gradientFrom: "from-sand",
      gradientTo: "to-coral",
      value: -1,
    },
    optionB: {
      label: "Fine dining experience",
      emoji: "🍽️",
      gradientFrom: "from-teal-deep",
      gradientTo: "to-teal-bright",
      value: 1,
    },
  },
  {
    id: 6,
    axis: "energy",
    question: "Evening atmosphere?",
    optionA: {
      label: "Live music and nightlife",
      emoji: "🎵",
      gradientFrom: "from-peach-light",
      gradientTo: "to-coral",
      value: 1,
    },
    optionB: {
      label: "Stargazing in silence",
      emoji: "⭐",
      gradientFrom: "from-teal-deep",
      gradientTo: "to-ocean",
      value: -1,
    },
  },
];

export const ARCHETYPE_DESCRIPTIONS: Record<
  TravelDNAArchetype,
  { description: string; icon: string; color: string }
> = {
  "Explorer-Wanderer": {
    description:
      "You crave spontaneous discovery and authentic experiences. You want to get lost in new places, connect with locals, and find the hidden gems that most tourists miss.",
    icon: "🗺️",
    color: "bg-teal-bright",
  },
  "Luxury Lounger": {
    description:
      "You believe travel is about comfort and indulgence. Fine dining, spa days, and premium accommodations are non-negotiable. You want the best experience money can buy.",
    icon: "✨",
    color: "bg-peach",
  },
  "Culture Seeker": {
    description:
      "You travel to understand the world. Museums, local customs, historical sites, and cultural immersion are what drive your wanderlust.",
    icon: "🏛️",
    color: "bg-teal-deep",
  },
  "Thrill Chaser": {
    description:
      "You live for adventure and adrenaline. Hiking, water sports, extreme activities, and pushing your limits define your perfect trip.",
    icon: "⚡",
    color: "bg-coral",
  },
  "Mindful Nomad": {
    description:
      "You travel to recharge and find inner peace. Yoga, meditation, nature, and slow travel are your ideal way to explore the world.",
    icon: "🧘",
    color: "bg-mint",
  },
};

export const SAMPLE_DESTINATIONS: Destination[] = [
  {
    id: "1",
    name: "Tokyo",
    country: "Japan",
    region: "Asia",
    lat: 35.6762,
    lng: 139.6503,
    description: "Vibrant metropolis blending ancient traditions with cutting-edge technology.",
    imageUrl: "https://images.unsplash.com/photo-1540959375944-7049f642e9a4?w=400",
    tags: ["urban", "culture", "food", "tech"],
    avgPrice: 1800,
    bestTime: "Mar-May, Sep-Nov",
  },
  {
    id: "2",
    name: "Bali",
    country: "Indonesia",
    region: "Asia",
    lat: -8.6705,
    lng: 115.2126,
    description: "Tropical paradise with beaches, temples, and rice terraces.",
    imageUrl: "https://images.unsplash.com/photo-1537225228614-b4fad34a2b08?w=400",
    tags: ["beach", "culture", "nature", "budget"],
    avgPrice: 800,
    bestTime: "Apr-Oct",
  },
  {
    id: "3",
    name: "Barcelona",
    country: "Spain",
    region: "Europe",
    lat: 41.3851,
    lng: 2.1734,
    description: "Catalan capital with Gaudí architecture and vibrant beach culture.",
    imageUrl: "https://images.unsplash.com/photo-1562883714-c7f02eb7bab7?w=400",
    tags: ["architecture", "beach", "culture", "food"],
    avgPrice: 1500,
    bestTime: "May-Jun, Sep-Oct",
  },
  {
    id: "4",
    name: "Machu Picchu",
    country: "Peru",
    region: "South America",
    lat: -13.1631,
    lng: -72.5471,
    description: "Ancient Incan citadel high in the Andes mountains.",
    imageUrl: "https://images.unsplash.com/photo-1587596635316-6f17e99f0cdb?w=400",
    tags: ["adventure", "history", "nature", "hiking"],
    avgPrice: 1200,
    bestTime: "May-Oct",
  },
  {
    id: "5",
    name: "Iceland",
    country: "Iceland",
    region: "Europe",
    lat: 65.1282,
    lng: -19.0182,
    description: "Land of fire and ice with waterfalls, glaciers, and geysers.",
    imageUrl: "https://images.unsplash.com/photo-1625074857471-5e3f3b70d2c9?w=400",
    tags: ["nature", "adventure", "photography", "unique"],
    avgPrice: 2200,
    bestTime: "Jun-Aug",
  },
  {
    id: "6",
    name: "Marrakech",
    country: "Morocco",
    region: "Africa",
    lat: 31.6295,
    lng: -8.0088,
    description: "Exotic medinas, riads, and desert adventures.",
    imageUrl: "https://images.unsplash.com/photo-1509027923473-77d33b20adbb?w=400",
    tags: ["culture", "food", "desert", "budget"],
    avgPrice: 900,
    bestTime: "Oct-Apr",
  },
  {
    id: "7",
    name: "Maldives",
    country: "Maldives",
    region: "Asia",
    lat: 4.1694,
    lng: 73.5067,
    description: "Crystal-clear waters, coral reefs, and overwater bungalows.",
    imageUrl: "https://images.unsplash.com/photo-1583588487-e37bc61ecab6?w=400",
    tags: ["beach", "luxury", "diving", "romantic"],
    avgPrice: 3500,
    bestTime: "Nov-Apr",
  },
  {
    id: "8",
    name: "Paris",
    country: "France",
    region: "Europe",
    lat: 48.8566,
    lng: 2.3522,
    description: "The City of Light with iconic landmarks and world-class museums.",
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400",
    tags: ["culture", "art", "food", "romantic"],
    avgPrice: 1800,
    bestTime: "Apr-Jun, Sep-Oct",
  },
  {
    id: "9",
    name: "New Zealand",
    country: "New Zealand",
    region: "Oceania",
    lat: -40.9006,
    lng: 174.886,
    description: "Dramatic landscapes perfect for adventure and outdoor activities.",
    imageUrl: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=400",
    tags: ["adventure", "nature", "hiking", "outdoor"],
    avgPrice: 2000,
    bestTime: "Dec-Feb",
  },
  {
    id: "10",
    name: "Dubai",
    country: "United Arab Emirates",
    region: "Middle East",
    lat: 25.2048,
    lng: 55.2708,
    description: "Ultra-modern city with luxury shopping, desert safaris, and beaches.",
    imageUrl: "https://images.unsplash.com/photo-1512453591867-ea9fb7c55bf6?w=400",
    tags: ["luxury", "shopping", "modern", "desert"],
    avgPrice: 2500,
    bestTime: "Nov-Mar",
  },
  {
    id: "11",
    name: "Bangkok",
    country: "Thailand",
    region: "Asia",
    lat: 13.7563,
    lng: 100.5018,
    description: "Bustling city with temples, street food, and vibrant nightlife.",
    imageUrl: "https://images.unsplash.com/photo-1508668778760-c94b03800b80?w=400",
    tags: ["culture", "food", "budget", "nightlife"],
    avgPrice: 900,
    bestTime: "Nov-Feb",
  },
  {
    id: "12",
    name: "Greece",
    country: "Greece",
    region: "Europe",
    lat: 37.9838,
    lng: 23.7275,
    description: "Island paradise with whitewashed villages and ancient ruins.",
    imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400",
    tags: ["beach", "culture", "romantic", "food"],
    avgPrice: 1400,
    bestTime: "May-Jun, Sep-Oct",
  },
];

export const BUDGET_RANGES = [
  { label: "Budget Explorer", min: 500, max: 1000, icon: "💰" },
  { label: "Comfortable Traveler", min: 1000, max: 2000, icon: "💳" },
  { label: "Premium Experience", min: 2000, max: 3500, icon: "💎" },
  { label: "Luxury Indulgence", min: 3500, max: 10000, icon: "👑" },
];

export const COMMON_DEPARTING_CITIES = [
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Phoenix",
  "Philadelphia",
  "San Antonio",
  "San Diego",
  "Dallas",
  "San Jose",
  "Austin",
  "Seattle",
  "Denver",
  "Boston",
  "Miami",
];

export const CONSTRAINTS_OPTIONS = {
  dietary: [
    "Vegetarian",
    "Vegan",
    "Gluten-free",
    "Kosher",
    "Halal",
    "No shellfish",
    "No dairy",
  ],
  mobility: ["Wheelchair accessible", "Limited mobility", "Requires assistance"],
  passport: ["US passport only", "Limited passport validity", "Visa restrictions"],
};
