import type { TravelDNAQuestion, TravelDNAArchetype, Destination } from "./types";

export const BRAND_COLORS = {
  teapDeep: "#0D7377",
  tealBright: "#14A3A8",
  tealLight: "#B2E4E6",
  peach: "#F4845F",
  peachLight: "#F7B89C",
  peachPale: "#FDE8DF",
  charcoal: "#2D3436",
  slate: "#636E72",
  silver: "#B2BEC3",
  cloud: "#F5F6FA",
  ocean: "#0A5C5E",
  coral: "#E17055",
  mint: "#55EFC4",
  sand: "#FFEAA7",
};

export const TRAVEL_DNA_QUESTIONS: TravelDNAQuestion[] = [
  {
    id: 1,
    axis: "social",
    question: "Your ideal evening?",
    optionA: {
      label: "Bustling night market",
      emoji: "\uD83C\uDF03",
      image: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=600&h=400&fit=crop",
      gradientFrom: "from-teal-deep",
      gradientTo: "to-teal-bright",
      value: 1,
    },
    optionB: {
      label: "Quiet sunset dinner",
      emoji: "\uD83C\uDF05",
      image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&h=400&fit=crop",
      gradientFrom: "from-peach",
      gradientTo: "to-peach-light",
      value: -1,
    },
  },
  {
    id: 2,
    axis: "adventure",
    question: "How do you start your travel days?",
    optionA: {
      label: "Wake up early for a hike",
      emoji: "\uD83C\uDFD4\uFE0F",
      image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&h=400&fit=crop",
      gradientFrom: "from-teal-bright",
      gradientTo: "to-mint",
      value: 1,
    },
    optionB: {
      label: "Sleep in, brunch at noon",
      emoji: "\uD83E\uDD50",
      image: "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=600&h=400&fit=crop",
      gradientFrom: "from-peach-light",
      gradientTo: "to-peach-pale",
      value: -1,
    },
  },
  {
    id: 3,
    axis: "structure",
    question: "When exploring a new place?",
    optionA: {
      label: "Guided tour with a local",
      emoji: "\uD83D\uDC68\u200D\uD83C\uDFEB",
      image: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600&h=400&fit=crop",
      gradientFrom: "from-teal-deep",
      gradientTo: "to-ocean",
      value: 1,
    },
    optionB: {
      label: "Wander and get lost",
      emoji: "\uD83D\uDDFA\uFE0F",
      image: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&h=400&fit=crop",
      gradientFrom: "from-coral",
      gradientTo: "to-peach",
      value: -1,
    },
  },
  {
    id: 4,
    axis: "cultural",
    question: "Where do you feel at home?",
    optionA: {
      label: "Mountain cabin",
      emoji: "\uD83C\uDFD4\uFE0F",
      image: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=600&h=400&fit=crop",
      gradientFrom: "from-teal-bright",
      gradientTo: "to-teal-light",
      value: -1,
    },
    optionB: {
      label: "Beachfront villa",
      emoji: "\uD83C\uDFDD\uFE0F",
      image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=600&h=400&fit=crop",
      gradientFrom: "from-peach",
      gradientTo: "to-sand",
      value: 1,
    },
  },
  {
    id: 5,
    axis: "budget",
    question: "How do you eat while traveling?",
    optionA: {
      label: "Street food crawl",
      emoji: "\uD83C\uDF2E",
      image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&h=400&fit=crop",
      gradientFrom: "from-sand",
      gradientTo: "to-coral",
      value: -1,
    },
    optionB: {
      label: "Fine dining experience",
      emoji: "\uD83C\uDF7D\uFE0F",
      image: "https://images.unsplash.com/photo-1550966871-3ed3cdb51f3a?w=600&h=400&fit=crop",
      gradientFrom: "from-teal-deep",
      gradientTo: "to-teal-bright",
      value: 1,
    },
  },
  {
    id: 6,
    axis: "energy",
    question: "Evening atmosphere?",
    optionA: {
      label: "Live music and nightlife",
      emoji: "\uD83C\uDFB5",
      image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&h=400&fit=crop",
      gradientFrom: "from-peach-light",
      gradientTo: "to-coral",
      value: 1,
    },
    optionB: {
      label: "Stargazing in silence",
      emoji: "\u2B50",
      image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600&h=400&fit=crop",
      gradientFrom: "from-teal-deep",
      gradientTo: "to-ocean",
      value: -1,
    },
  },
];

export const ARCHETYPE_DESCRIPTIONS: Record<
  TravelDNAArchetype,
  { description: string; icon: string; color: string }
> = {
  "Explorer-Wanderer": {
    description:
      "You crave spontaneous discovery and authentic experiences. You want to get lost in new places, connect with locals, and find the hidden gems that most tourists miss.",
    icon: "🗺️",
    color: "bg-teal-bright",
  },
  "Luxury Lounger": {
    description:
      "You believe travel is about comfort and indulgence. Fine dining, spa days, and premium accommodations are non-negotiable. You want the best experience money can buy.",
    icon: "✨",
    color: "bg-peach",
  },
  "Culture Seeker": {
    description:
      "You travel to understand the world. Museums, local customs, historical sites, and cultural immersion are what drive your wanderlust.",
    icon: "🏛️",
    color: "bg-teal-deep",
  },
  "Thrill Chaser": {
    description:
      "You live for adventure and adrenaline. Hiking, water sports, extreme activities, and pushing your limits define your perfect trip.",
    icon: "⚡",
    color: "bg-coral",
  },
  "Mindful Nomad": {
    description:
      "You travel to recharge and find inner peace. Yoga, meditation, nature, and slow travel are your ideal way to explore the world.",
    icon: "🧘",
    color: "bg-mint",
  },
};

export const SAMPLE_DESTINATIONS: Destination[] = [
  {
    id: "1",
    name: "Tokyo",
    country: "Japan",
    region: "Asia",
    lat: 35.6762,
    lng: 139.6503,
    description: "Vibrant metropolis blending ancient traditions with cutting-edge technology.",
    imageUrl: "https://images.unsplash.com/photo-1540959375944-7049f642e9a4?w=400",
    tags: ["urban", "culture", "food", "tech"],
    avgPrice: 1800,
    bestTime: "Mar-May, Sep-Nov",
  },
  {
    id: "2",
    name: "Bali",
    country: "Indonesia",
    region: "Asia",
    lat: -8.6705,
    lng: 115.2126,
    description: "Tropical paradise with beaches, temples, and rice terraces.",
    imageUrl: "https://images.unsplash.com/photo-1537225228614-b4fad34a2b08?w=400",
    tags: ["beach", "culture", "nature", "budget"],
    avgPrice: 800,
    bestTime: "Apr-Oct",
  },
  {
    id: "3",
    name: "Barcelona",
    country: "Spain",
    region: "Europe",
    lat: 41.3851,
    lng: 2.1734,
    description: "Catalan capital with Gaudí architecture and vibrant beach culture.",
    imageUrl: "https://images.unsplash.com/photo-1562883714-c7f02eb7bab7?w=400",
    tags: ["architecture", "beach", "culture", "food"],
    avgPrice: 1500,
    bestTime: "May-Jun, Sep-Oct",
  },
  {
    id: "4",
    name: "Machu Picchu",
    country: "Peru",
    region: "South America",
    lat: -13.1631,
    lng: -72.5471,
    description: "Ancient Incan citadel high in the Andes mountains.",
    imageUrl: "https://images.unsplash.com/photo-1587596635316-6f17e99f0cdb?w=400",
    tags: ["adventure", "history", "nature", "hiking"],
    avgPrice: 1200,
    bestTime: "May-Oct",
  },
  {
    id: "5",
    name: "Iceland",
    country: "Iceland",
    region: "Europe",
    lat: 65.1282,
    lng: -19.0182,
    description: "Land of fire and ice with waterfalls, glaciers, and geysers.",
    imageUrl: "https://images.unsplash.com/photo-1625074857471-5e3f3b70d2c9?w=400",
    tags: ["nature", "adventure", "photography", "unique"],
    avgPrice: 2200,
    bestTime: "Jun-Aug",
  },
  {
    id: "6",
    name: "Marrakech",
    country: "Morocco",
    region: "Africa",
    lat: 31.6295,
    lng: -8.0088,
    description: "Exotic medinas, riads, and desert adventures.",
    imageUrl: "https://images.unsplash.com/photo-1509027923473-77d33b20adbb?w=400",
    tags: ["culture", "food", "desert", "budget"],
    avgPrice: 900,
    bestTime: "Oct-Apr",
  },
  {
    id: "7",
    name: "Maldives",
    country: "Maldives",
    region: "Asia",
    lat: 4.1694,
    lng: 73.5067,
    description: "Crystal-clear waters, coral reefs, and overwater bungalows.",
    imageUrl: "https://images.unsplash.com/photo-1583588487-e37bc61ecab6?w=400",
    tags: ["beach", "luxury", "diving", "romantic"],
    avgPrice: 3500,
    bestTime: "Nov-Apr",
  },
  {
    id: "8",
    name: "Paris",
    country: "France",
    region: "Europe",
    lat: 48.8566,
    lng: 2.3522,
    description: "The City of Light with iconic landmarks and world-class museums.",
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400",
    tags: ["culture", "art", "food", "romantic"],
    avgPrice: 1800,
    bestTime: "Apr-Jun, Sep-Oct",
  },
  {
    id: "9",
    name: "New Zealand",
    country: "New Zealand",
    region: "Oceania",
    lat: -40.9006,
    lng: 174.886,
    description: "Dramatic landscapes perfect for adventure and outdoor activities.",
    imageUrl: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=400",
    tags: ["adventure", "nature", "hiking", "outdoor"],
    avgPrice: 2000,
    bestTime: "Dec-Feb",
  },
  {
    id: "10",
    name: "Dubai",
    country: "United Arab Emirates",
    region: "Middle East",
    lat: 25.2048,
    lng: 55.2708,
    description: "Ultra-modern city with luxury shopping, desert safaris, and beaches.",
    imageUrl: "https://images.unsplash.com/photo-1512453591867-ea9fb7c55bf6?w=400",
    tags: ["luxury", "shopping", "modern", "desert"],
    avgPrice: 2500,
    bestTime: "Nov-Mar",
  },
  {
    id: "11",
    name: "Bangkok",
    country: "Thailand",
    region: "Asia",
    lat: 13.7563,
    lng: 100.5018,
    description: "Bustling city with temples, street food, and vibrant nightlife.",
    imageUrl: "https://images.unsplash.com/photo-1508668778760-c94b03800b80?w=400",
    tags: ["culture", "food", "budget", "nightlife"],
    avgPrice: 900,
    bestTime: "Nov-Feb",
  },
  {
    id: "12",
    name: "Greece",
    country: "Greece",
    region: "Europe",
    lat: 37.9838,
    lng: 23.7275,
    description: "Island paradise with whitewashed villages and ancient ruins.",
    imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400",
    tags: ["beach", "culture", "romantic", "food"],
    avgPrice: 1400,
    bestTime: "May-Jun, Sep-Oct",
  },
];

// Domestic / drivable destinations
export const DOMESTIC_DESTINATIONS: Destination[] = [
  {
    id: "d1",
    name: "Sedona",
    country: "USA",
    region: "Domestic",
    lat: 34.8697,
    lng: -111.7610,
    description: "Red rock canyons, desert hikes, and spiritual energy vortexes.",
    imageUrl: "https://images.unsplash.com/photo-1518098268026-4e89f1a2cd8e?w=400",
    tags: ["nature", "hiking", "photography", "unique"],
    avgPrice: 600,
    bestTime: "Mar-May, Sep-Nov",
  },
  {
    id: "d2",
    name: "San Diego",
    country: "USA",
    region: "Domestic",
    lat: 32.7157,
    lng: -117.1611,
    description: "Beaches, craft beer, world-class zoo, and year-round sun.",
    imageUrl: "https://images.unsplash.com/photo-1538097304804-2a1b932466a9?w=400",
    tags: ["beach", "food", "urban", "outdoor"],
    avgPrice: 700,
    bestTime: "Year-round",
  },
  {
    id: "d3",
    name: "Nashville",
    country: "USA",
    region: "Domestic",
    lat: 36.1627,
    lng: -86.7816,
    description: "Live music capital with honky-tonks, hot chicken, and southern charm.",
    imageUrl: "https://images.unsplash.com/photo-1545419913-775facd0ce96?w=400",
    tags: ["nightlife", "food", "culture", "urban"],
    avgPrice: 550,
    bestTime: "Apr-Jun, Sep-Oct",
  },
  {
    id: "d4",
    name: "Big Sur",
    country: "USA",
    region: "Domestic",
    lat: 36.2704,
    lng: -121.8081,
    description: "Dramatic Pacific coastline with cliffs, redwoods, and ocean views.",
    imageUrl: "https://images.unsplash.com/photo-1449034446853-66c86144b0ad?w=400",
    tags: ["nature", "photography", "romantic", "hiking"],
    avgPrice: 800,
    bestTime: "Apr-Nov",
  },
  {
    id: "d5",
    name: "New Orleans",
    country: "USA",
    region: "Domestic",
    lat: 29.9511,
    lng: -90.0715,
    description: "Jazz, Cajun cuisine, French Quarter, and unforgettable nightlife.",
    imageUrl: "https://images.unsplash.com/photo-1568402102990-bc541580b59f?w=400",
    tags: ["culture", "food", "nightlife", "history"],
    avgPrice: 600,
    bestTime: "Feb-May, Oct-Nov",
  },
  {
    id: "d6",
    name: "Savannah",
    country: "USA",
    region: "Domestic",
    lat: 32.0809,
    lng: -81.0912,
    description: "Moss-draped oaks, historic squares, and coastal Southern elegance.",
    imageUrl: "https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=400",
    tags: ["history", "romantic", "culture", "food"],
    avgPrice: 500,
    bestTime: "Mar-May, Oct-Nov",
  },
  {
    id: "d7",
    name: "Moab",
    country: "USA",
    region: "Domestic",
    lat: 38.5733,
    lng: -109.5498,
    description: "Gateway to Arches and Canyonlands with world-class mountain biking.",
    imageUrl: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=400",
    tags: ["adventure", "hiking", "nature", "outdoor"],
    avgPrice: 500,
    bestTime: "Mar-May, Sep-Nov",
  },
  {
    id: "d8",
    name: "Austin",
    country: "USA",
    region: "Domestic",
    lat: 30.2672,
    lng: -97.7431,
    description: "Live music, tech culture, BBQ, and a famously weird vibe.",
    imageUrl: "https://images.unsplash.com/photo-1531218150217-54595bc2b934?w=400",
    tags: ["nightlife", "food", "urban", "culture"],
    avgPrice: 600,
    bestTime: "Mar-May, Sep-Nov",
  },
  {
    id: "d9",
    name: "Yellowstone",
    country: "USA",
    region: "Domestic",
    lat: 44.4280,
    lng: -110.5885,
    description: "Geysers, hot springs, bison herds, and vast wilderness.",
    imageUrl: "https://images.unsplash.com/photo-1527549993586-dff825b37782?w=400",
    tags: ["nature", "adventure", "photography", "unique"],
    avgPrice: 700,
    bestTime: "Jun-Sep",
  },
  {
    id: "d10",
    name: "Charleston",
    country: "USA",
    region: "Domestic",
    lat: 32.7765,
    lng: -79.9311,
    description: "Pastel-colored historic district, award-winning restaurants, and beaches.",
    imageUrl: "https://images.unsplash.com/photo-1569880153113-76e33fc52b5f?w=400",
    tags: ["history", "food", "romantic", "beach"],
    avgPrice: 600,
    bestTime: "Mar-May, Sep-Nov",
  },
];

// All destinations combined (international + domestic)
export const ALL_DESTINATIONS: Destination[] = [...SAMPLE_DESTINATIONS, ...DOMESTIC_DESTINATIONS];

// Approximate lat/lng for common US departure cities (for drive time calculation)
export const DEPARTURE_CITY_COORDS: Record<string, { lat: number; lng: number }> = {
  "New York": { lat: 40.7128, lng: -74.0060 },
  "Los Angeles": { lat: 34.0522, lng: -118.2437 },
  "Chicago": { lat: 41.8781, lng: -87.6298 },
  "Houston": { lat: 29.7604, lng: -95.3698 },
  "Phoenix": { lat: 33.4484, lng: -112.0740 },
  "Philadelphia": { lat: 39.9526, lng: -75.1652 },
  "San Antonio": { lat: 29.4241, lng: -98.4936 },
  "San Diego": { lat: 32.7157, lng: -117.1611 },
  "Dallas": { lat: 32.7767, lng: -96.7970 },
  "San Jose": { lat: 37.3382, lng: -121.8863 },
  "Austin": { lat: 30.2672, lng: -97.7431 },
  "Seattle": { lat: 47.6062, lng: -122.3321 },
  "Denver": { lat: 39.7392, lng: -104.9903 },
  "Boston": { lat: 42.3601, lng: -71.0589 },
  "Miami": { lat: 25.7617, lng: -80.1918 },
};

export const BUDGET_RANGES = [
  { label: "Budget Explorer", min: 500, max: 1000, icon: "💰" },
  { label: "Comfortable Traveler", min: 1000, max: 2000, icon: "💳" },
  { label: "Premium Experience", min: 2000, max: 3500, icon: "💎" },
  { label: "Luxury Indulgence", min: 3500, max: 10000, icon: "👑" },
];

export const COMMON_DEPARTING_CITIES = [
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Phoenix",
  "Philadelphia",
  "San Antonio",
  "San Diego",
  "Dallas",
  "San Jose",
  "Austin",
  "Seattle",
  "Denver",
  "Boston",
  "Miami",
];

export const CONSTRAINTS_OPTIONS = {
  dietary: [
    "Vegetarian",
    "Vegan",
    "Gluten-free",
    "Kosher",
    "Halal",
    "No shellfish",
    "No dairy",
  ],
  mobility: ["Wheelchair accessible", "Limited mobility", "Requires assistance"],
  passport: ["US passport only", "Limited passport validity", "Visa restrictions"],
};
